// Do not edit this file. It is auto-generated from org.sireum.amandroid.module.AndroidFixPilarSymbolResolver
// by org.sireum.pipeline.gen.ModuleGenerator

package org.sireum.amandroid.module

import org.sireum.util._
import org.sireum.pipeline._
import org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables
import org.sireum.amandroid.objectFlowAnalysis.PrepareApp
import org.sireum.pilar.ast.Model
import org.sireum.pilar.symbol.SymbolTable
import scala.Option
import scala.collection.immutable.Seq

object AndroidFixPilarSymbolResolverModule extends PipelineModule {
  def title = "Fix Pilar Symbol Resolver for Android"
  def origin = classOf[AndroidFixPilarSymbolResolver]

  val globalParallelKey = "Global.parallel"
  val globalAndroidLibInfoTablesOptKey = "Global.androidLibInfoTablesOpt"
  val globalAppInfoKey = "Global.appInfo"
  val globalModelsKey = "Global.models"
  val globalShouldBuildLibInfoTablesKey = "Global.shouldBuildLibInfoTables"
  val globalSymbolTableKey = "Global.symbolTable"

  def compute(job : PipelineJob, info : PipelineJobModuleInfo) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    try {
      val module = Class.forName("org.sireum.amandroid.module.AndroidFixPilarSymbolResolverModuleDef")
      val cons = module.getConstructors()(0)
      val params = Array[AnyRef](job, info)
      val inst = cons.newInstance(params : _*)
    } catch {
      case e : Throwable =>
        e.printStackTrace
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, e.getMessage);
    }
    return tags
  }

  override def initialize(job : PipelineJob) {
    if(!(job ? AndroidFixPilarSymbolResolverModule.globalShouldBuildLibInfoTablesKey)) {
      val shouldBuildLibInfoTables = Class.forName("org.sireum.amandroid.module.AndroidFixPilarSymbolResolver").getDeclaredMethod("$lessinit$greater$default$3").invoke(null).asInstanceOf[scala.Boolean]
      setShouldBuildLibInfoTables(job.propertyMap, shouldBuildLibInfoTables)
    }
  }

  override def validPipeline(stage : PipelineStage, job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    val deps = ilist[PipelineModule]()
    deps.foreach(d =>
      if(stage.modules.contains(d)){
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "'" + this.title + "' depends on '" + d.title + "' yet both were found in stage '" + stage.title + "'"
        )
      }
    )
    return tags
  }

  def inputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    var _parallel : scala.Option[AnyRef] = None
    var _parallelKey : scala.Option[String] = None

    val keylistparallel = List(AndroidFixPilarSymbolResolverModule.globalParallelKey)
    keylistparallel.foreach(key => 
      if(job ? key) { 
        if(_parallel.isEmpty) {
          _parallel = Some(job(key))
          _parallelKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _parallel.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'parallel' keys '" + _parallelKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _parallel match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.Boolean]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'parallel'.  Expecting 'scala.Boolean' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'parallel'")       
    }
    var _shouldBuildLibInfoTables : scala.Option[AnyRef] = None
    var _shouldBuildLibInfoTablesKey : scala.Option[String] = None

    val keylistshouldBuildLibInfoTables = List(AndroidFixPilarSymbolResolverModule.globalShouldBuildLibInfoTablesKey)
    keylistshouldBuildLibInfoTables.foreach(key => 
      if(job ? key) { 
        if(_shouldBuildLibInfoTables.isEmpty) {
          _shouldBuildLibInfoTables = Some(job(key))
          _shouldBuildLibInfoTablesKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _shouldBuildLibInfoTables.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'shouldBuildLibInfoTables' keys '" + _shouldBuildLibInfoTablesKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _shouldBuildLibInfoTables match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.Boolean]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'shouldBuildLibInfoTables'.  Expecting 'scala.Boolean' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'shouldBuildLibInfoTables'")       
    }
    var _appInfo : scala.Option[AnyRef] = None
    var _appInfoKey : scala.Option[String] = None

    val keylistappInfo = List(AndroidFixPilarSymbolResolverModule.globalAppInfoKey)
    keylistappInfo.foreach(key => 
      if(job ? key) { 
        if(_appInfo.isEmpty) {
          _appInfo = Some(job(key))
          _appInfoKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _appInfo.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'appInfo' keys '" + _appInfoKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _appInfo match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.amandroid.objectFlowAnalysis.PrepareApp]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'appInfo'.  Expecting 'org.sireum.amandroid.objectFlowAnalysis.PrepareApp' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'appInfo'")       
    }
    var _models : scala.Option[AnyRef] = None
    var _modelsKey : scala.Option[String] = None

    val keylistmodels = List(AndroidFixPilarSymbolResolverModule.globalModelsKey)
    keylistmodels.foreach(key => 
      if(job ? key) { 
        if(_models.isEmpty) {
          _models = Some(job(key))
          _modelsKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _models.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'models' keys '" + _modelsKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _models match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'models'.  Expecting 'scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'models'")       
    }
    return tags
  }

  def outputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    if(!(job ? AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey)) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': No entry found for 'androidLibInfoTablesOpt'. Expecting (AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey)") 
    }

    if(job ? AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey && !job(AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey).isInstanceOf[scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey.  Expecting 'scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]' but found '" + 
        job(AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey).getClass.toString + "'")
    } 

    if(!(job ? AndroidFixPilarSymbolResolverModule.globalSymbolTableKey)) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': No entry found for 'symbolTable'. Expecting (AndroidFixPilarSymbolResolverModule.globalSymbolTableKey)") 
    }

    if(job ? AndroidFixPilarSymbolResolverModule.globalSymbolTableKey && !job(AndroidFixPilarSymbolResolverModule.globalSymbolTableKey).isInstanceOf[org.sireum.pilar.symbol.SymbolTable]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for AndroidFixPilarSymbolResolverModule.globalSymbolTableKey.  Expecting 'org.sireum.pilar.symbol.SymbolTable' but found '" + 
        job(AndroidFixPilarSymbolResolverModule.globalSymbolTableKey).getClass.toString + "'")
    } 
    return tags
  }

  def getParallel (options : scala.collection.Map[Property.Key, Any]) : scala.Boolean = {
    if (options.contains(AndroidFixPilarSymbolResolverModule.globalParallelKey)) {
       return options(AndroidFixPilarSymbolResolverModule.globalParallelKey).asInstanceOf[scala.Boolean]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setParallel (options : MMap[Property.Key, Any], parallel : scala.Boolean) : MMap[Property.Key, Any] = {

    options(AndroidFixPilarSymbolResolverModule.globalParallelKey) = parallel

    return options
  }

  def getShouldBuildLibInfoTables (options : scala.collection.Map[Property.Key, Any]) : scala.Boolean = {
    if (options.contains(AndroidFixPilarSymbolResolverModule.globalShouldBuildLibInfoTablesKey)) {
       return options(AndroidFixPilarSymbolResolverModule.globalShouldBuildLibInfoTablesKey).asInstanceOf[scala.Boolean]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setShouldBuildLibInfoTables (options : MMap[Property.Key, Any], shouldBuildLibInfoTables : scala.Boolean) : MMap[Property.Key, Any] = {

    options(AndroidFixPilarSymbolResolverModule.globalShouldBuildLibInfoTablesKey) = shouldBuildLibInfoTables

    return options
  }

  def getAppInfo (options : scala.collection.Map[Property.Key, Any]) : org.sireum.amandroid.objectFlowAnalysis.PrepareApp = {
    if (options.contains(AndroidFixPilarSymbolResolverModule.globalAppInfoKey)) {
       return options(AndroidFixPilarSymbolResolverModule.globalAppInfoKey).asInstanceOf[org.sireum.amandroid.objectFlowAnalysis.PrepareApp]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setAppInfo (options : MMap[Property.Key, Any], appInfo : org.sireum.amandroid.objectFlowAnalysis.PrepareApp) : MMap[Property.Key, Any] = {

    options(AndroidFixPilarSymbolResolverModule.globalAppInfoKey) = appInfo

    return options
  }

  def getModels (options : scala.collection.Map[Property.Key, Any]) : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = {
    if (options.contains(AndroidFixPilarSymbolResolverModule.globalModelsKey)) {
       return options(AndroidFixPilarSymbolResolverModule.globalModelsKey).asInstanceOf[scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setModels (options : MMap[Property.Key, Any], models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]) : MMap[Property.Key, Any] = {

    options(AndroidFixPilarSymbolResolverModule.globalModelsKey) = models

    return options
  }

  def getAndroidLibInfoTablesOpt (options : scala.collection.Map[Property.Key, Any]) : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables] = {
    if (options.contains(AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey)) {
       return options(AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey).asInstanceOf[scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setAndroidLibInfoTablesOpt (options : MMap[Property.Key, Any], androidLibInfoTablesOpt : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]) : MMap[Property.Key, Any] = {

    options(AndroidFixPilarSymbolResolverModule.globalAndroidLibInfoTablesOptKey) = androidLibInfoTablesOpt

    return options
  }

  def getSymbolTable (options : scala.collection.Map[Property.Key, Any]) : org.sireum.pilar.symbol.SymbolTable = {
    if (options.contains(AndroidFixPilarSymbolResolverModule.globalSymbolTableKey)) {
       return options(AndroidFixPilarSymbolResolverModule.globalSymbolTableKey).asInstanceOf[org.sireum.pilar.symbol.SymbolTable]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setSymbolTable (options : MMap[Property.Key, Any], symbolTable : org.sireum.pilar.symbol.SymbolTable) : MMap[Property.Key, Any] = {

    options(AndroidFixPilarSymbolResolverModule.globalSymbolTableKey) = symbolTable

    return options
  }

  object ConsumerView {
    implicit class AndroidFixPilarSymbolResolverModuleConsumerView (val job : PropertyProvider) extends AnyVal {
      def parallel : scala.Boolean = AndroidFixPilarSymbolResolverModule.getParallel(job.propertyMap)
      def shouldBuildLibInfoTables : scala.Boolean = AndroidFixPilarSymbolResolverModule.getShouldBuildLibInfoTables(job.propertyMap)
      def appInfo : org.sireum.amandroid.objectFlowAnalysis.PrepareApp = AndroidFixPilarSymbolResolverModule.getAppInfo(job.propertyMap)
      def models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = AndroidFixPilarSymbolResolverModule.getModels(job.propertyMap)
      def androidLibInfoTablesOpt : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables] = AndroidFixPilarSymbolResolverModule.getAndroidLibInfoTablesOpt(job.propertyMap)
      def symbolTable : org.sireum.pilar.symbol.SymbolTable = AndroidFixPilarSymbolResolverModule.getSymbolTable(job.propertyMap)
    }
  }

  object ProducerView {
    implicit class AndroidFixPilarSymbolResolverModuleProducerView (val job : PropertyProvider) extends AnyVal {

      def parallel_=(parallel : scala.Boolean) { AndroidFixPilarSymbolResolverModule.setParallel(job.propertyMap, parallel) }
      def parallel : scala.Boolean = AndroidFixPilarSymbolResolverModule.getParallel(job.propertyMap)

      def shouldBuildLibInfoTables_=(shouldBuildLibInfoTables : scala.Boolean) { AndroidFixPilarSymbolResolverModule.setShouldBuildLibInfoTables(job.propertyMap, shouldBuildLibInfoTables) }
      def shouldBuildLibInfoTables : scala.Boolean = AndroidFixPilarSymbolResolverModule.getShouldBuildLibInfoTables(job.propertyMap)

      def appInfo_=(appInfo : org.sireum.amandroid.objectFlowAnalysis.PrepareApp) { AndroidFixPilarSymbolResolverModule.setAppInfo(job.propertyMap, appInfo) }
      def appInfo : org.sireum.amandroid.objectFlowAnalysis.PrepareApp = AndroidFixPilarSymbolResolverModule.getAppInfo(job.propertyMap)

      def models_=(models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]) { AndroidFixPilarSymbolResolverModule.setModels(job.propertyMap, models) }
      def models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = AndroidFixPilarSymbolResolverModule.getModels(job.propertyMap)

      def androidLibInfoTablesOpt_=(androidLibInfoTablesOpt : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]) { AndroidFixPilarSymbolResolverModule.setAndroidLibInfoTablesOpt(job.propertyMap, androidLibInfoTablesOpt) }
      def androidLibInfoTablesOpt : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables] = AndroidFixPilarSymbolResolverModule.getAndroidLibInfoTablesOpt(job.propertyMap)

      def symbolTable_=(symbolTable : org.sireum.pilar.symbol.SymbolTable) { AndroidFixPilarSymbolResolverModule.setSymbolTable(job.propertyMap, symbolTable) }
      def symbolTable : org.sireum.pilar.symbol.SymbolTable = AndroidFixPilarSymbolResolverModule.getSymbolTable(job.propertyMap)
    }
  }
}

trait AndroidFixPilarSymbolResolverModule {
  def job : PipelineJob

  def parallel : scala.Boolean = AndroidFixPilarSymbolResolverModule.getParallel(job.propertyMap)

  def shouldBuildLibInfoTables : scala.Boolean = AndroidFixPilarSymbolResolverModule.getShouldBuildLibInfoTables(job.propertyMap)

  def appInfo : org.sireum.amandroid.objectFlowAnalysis.PrepareApp = AndroidFixPilarSymbolResolverModule.getAppInfo(job.propertyMap)

  def models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = AndroidFixPilarSymbolResolverModule.getModels(job.propertyMap)


  def androidLibInfoTablesOpt_=(androidLibInfoTablesOpt : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]) { AndroidFixPilarSymbolResolverModule.setAndroidLibInfoTablesOpt(job.propertyMap, androidLibInfoTablesOpt) }
  def androidLibInfoTablesOpt : scala.Option[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables] = AndroidFixPilarSymbolResolverModule.getAndroidLibInfoTablesOpt(job.propertyMap)


  def symbolTable_=(symbolTable : org.sireum.pilar.symbol.SymbolTable) { AndroidFixPilarSymbolResolverModule.setSymbolTable(job.propertyMap, symbolTable) }
  def symbolTable : org.sireum.pilar.symbol.SymbolTable = AndroidFixPilarSymbolResolverModule.getSymbolTable(job.propertyMap)
}