// Do not edit this file. It is auto-generated from org.sireum.amandroid.module.OFAPreprocess
// by org.sireum.pipeline.gen.ModuleGenerator

package org.sireum.amandroid.module

import org.sireum.util._
import org.sireum.pipeline._
import java.lang.String
import org.sireum.alir.AlirIntraProceduralNode
import org.sireum.alir.ControlFlowGraph
import org.sireum.alir.DefRef
import org.sireum.alir.MonotoneDataFlowAnalysisResult
import org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables
import org.sireum.amandroid.module.AndroidInterIntraProcedural.AndroidInterAnalysisResult
import org.sireum.amandroid.module.AndroidInterIntraProcedural.AndroidIntraAnalysisResult
import org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph
import org.sireum.amandroid.objectflowanalysis.OfaNode
import org.sireum.pilar.ast.LocationDecl
import org.sireum.pilar.symbol.ProcedureSymbolTable
import org.sireum.pilar.symbol.SymbolTable
import scala.Function1
import scala.Function2
import scala.Option
import scala.collection.mutable.Map

object OFAPreprocessModule extends PipelineModule {
  def title = "intra object flow graph Build"
  def origin = classOf[OFAPreprocess]

  val globalProcedureSymbolTableKey = "Global.procedureSymbolTable"
  val cfgKey = "OFAPreprocess.cfg"
  val globalRdaKey = "Global.rda"
  val globalAndroidVirtualMethodTablesKey = "Global.androidVirtualMethodTables"
  val globalOFGKey = "Global.OFG"
  val globalCfgKey = "Global.cfg"
  val rdaKey = "OFAPreprocess.rda"
  val OFGKey = "OFAPreprocess.OFG"

  def compute(job : PipelineJob, info : PipelineJobModuleInfo) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    try {
      val module = Class.forName("org.sireum.amandroid.module.OFAPreprocessModuleDef")
      val cons = module.getConstructors()(0)
      val params = Array[AnyRef](job, info)
      val inst = cons.newInstance(params : _*)
    } catch {
      case e : Throwable =>
        e.printStackTrace
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, e.getMessage);
    }
    return tags
  }

  override def initialize(job : PipelineJob) {
  }

  override def validPipeline(stage : PipelineStage, job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    val deps = ilist[PipelineModule](CfgModule, RdaModule)
    deps.foreach(d =>
      if(stage.modules.contains(d)){
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "'" + this.title + "' depends on '" + d.title + "' yet both were found in stage '" + stage.title + "'"
        )
      }
    )
    return tags
  }

  def inputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    var _procedureSymbolTable : scala.Option[AnyRef] = None
    var _procedureSymbolTableKey : scala.Option[String] = None

    val keylistprocedureSymbolTable = List(OFAPreprocessModule.globalProcedureSymbolTableKey)
    keylistprocedureSymbolTable.foreach(key => 
      if(job ? key) { 
        if(_procedureSymbolTable.isEmpty) {
          _procedureSymbolTable = Some(job(key))
          _procedureSymbolTableKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _procedureSymbolTable.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'procedureSymbolTable' keys '" + _procedureSymbolTableKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _procedureSymbolTable match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.pilar.symbol.ProcedureSymbolTable]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'procedureSymbolTable'.  Expecting 'org.sireum.pilar.symbol.ProcedureSymbolTable' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'procedureSymbolTable'")       
    }
    var _cfg : scala.Option[AnyRef] = None
    var _cfgKey : scala.Option[String] = None

    val keylistcfg = List(OFAPreprocessModule.globalCfgKey, CfgModule.cfgKey)
    keylistcfg.foreach(key => 
      if(job ? key) { 
        if(_cfg.isEmpty) {
          _cfg = Some(job(key))
          _cfgKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _cfg.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'cfg' keys '" + _cfgKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _cfg match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.alir.ControlFlowGraph[java.lang.String]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'cfg'.  Expecting 'org.sireum.alir.ControlFlowGraph[java.lang.String]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'cfg'")       
    }
    var _androidVirtualMethodTables : scala.Option[AnyRef] = None
    var _androidVirtualMethodTablesKey : scala.Option[String] = None

    val keylistandroidVirtualMethodTables = List(OFAPreprocessModule.globalAndroidVirtualMethodTablesKey)
    keylistandroidVirtualMethodTables.foreach(key => 
      if(job ? key) { 
        if(_androidVirtualMethodTables.isEmpty) {
          _androidVirtualMethodTables = Some(job(key))
          _androidVirtualMethodTablesKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _androidVirtualMethodTables.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'androidVirtualMethodTables' keys '" + _androidVirtualMethodTablesKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _androidVirtualMethodTables match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'androidVirtualMethodTables'.  Expecting 'org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'androidVirtualMethodTables'")       
    }
    var _rda : scala.Option[AnyRef] = None
    var _rdaKey : scala.Option[String] = None

    val keylistrda = List(OFAPreprocessModule.globalRdaKey, RdaModule.rdaKey)
    keylistrda.foreach(key => 
      if(job ? key) { 
        if(_rda.isEmpty) {
          _rda = Some(job(key))
          _rdaKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _rda.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'rda' keys '" + _rdaKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _rda match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'rda'.  Expecting 'org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'rda'")       
    }
    return tags
  }

  def outputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    if(!(job ? OFAPreprocessModule.OFGKey) && !(job ? OFAPreprocessModule.globalOFGKey)) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': No entry found for 'OFG'. Expecting (OFAPreprocessModule.OFGKey or OFAPreprocessModule.globalOFGKey)") 
    }

    if(job ? OFAPreprocessModule.OFGKey && !job(OFAPreprocessModule.OFGKey).isInstanceOf[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for OFAPreprocessModule.OFGKey.  Expecting 'org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]' but found '" + 
        job(OFAPreprocessModule.OFGKey).getClass.toString + "'")
    } 

    if(job ? OFAPreprocessModule.globalOFGKey && !job(OFAPreprocessModule.globalOFGKey).isInstanceOf[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for OFAPreprocessModule.globalOFGKey.  Expecting 'org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]' but found '" + 
        job(OFAPreprocessModule.globalOFGKey).getClass.toString + "'")
    } 
    return tags
  }

  def getProcedureSymbolTable (options : scala.collection.Map[Property.Key, Any]) : org.sireum.pilar.symbol.ProcedureSymbolTable = {
    if (options.contains(OFAPreprocessModule.globalProcedureSymbolTableKey)) {
       return options(OFAPreprocessModule.globalProcedureSymbolTableKey).asInstanceOf[org.sireum.pilar.symbol.ProcedureSymbolTable]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setProcedureSymbolTable (options : MMap[Property.Key, Any], procedureSymbolTable : org.sireum.pilar.symbol.ProcedureSymbolTable) : MMap[Property.Key, Any] = {

    options(OFAPreprocessModule.globalProcedureSymbolTableKey) = procedureSymbolTable

    return options
  }

  def getCfg (options : scala.collection.Map[Property.Key, Any]) : org.sireum.alir.ControlFlowGraph[java.lang.String] = {
    if (options.contains(OFAPreprocessModule.globalCfgKey)) {
       return options(OFAPreprocessModule.globalCfgKey).asInstanceOf[org.sireum.alir.ControlFlowGraph[java.lang.String]]
    }
    if (options.contains(OFAPreprocessModule.cfgKey)) {
       return options(OFAPreprocessModule.cfgKey).asInstanceOf[org.sireum.alir.ControlFlowGraph[java.lang.String]]
    }
    if (options.contains(CfgModule.cfgKey)) {
       return options(CfgModule.cfgKey).asInstanceOf[org.sireum.alir.ControlFlowGraph[java.lang.String]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setCfg (options : MMap[Property.Key, Any], cfg : org.sireum.alir.ControlFlowGraph[java.lang.String]) : MMap[Property.Key, Any] = {

    options(OFAPreprocessModule.globalCfgKey) = cfg
    options(cfgKey) = cfg

    return options
  }

  def getAndroidVirtualMethodTables (options : scala.collection.Map[Property.Key, Any]) : org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables = {
    if (options.contains(OFAPreprocessModule.globalAndroidVirtualMethodTablesKey)) {
       return options(OFAPreprocessModule.globalAndroidVirtualMethodTablesKey).asInstanceOf[org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setAndroidVirtualMethodTables (options : MMap[Property.Key, Any], androidVirtualMethodTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables) : MMap[Property.Key, Any] = {

    options(OFAPreprocessModule.globalAndroidVirtualMethodTablesKey) = androidVirtualMethodTables

    return options
  }

  def getRda (options : scala.collection.Map[Property.Key, Any]) : org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]] = {
    if (options.contains(OFAPreprocessModule.globalRdaKey)) {
       return options(OFAPreprocessModule.globalRdaKey).asInstanceOf[org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]
    }
    if (options.contains(OFAPreprocessModule.rdaKey)) {
       return options(OFAPreprocessModule.rdaKey).asInstanceOf[org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]
    }
    if (options.contains(RdaModule.rdaKey)) {
       return options(RdaModule.rdaKey).asInstanceOf[org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setRda (options : MMap[Property.Key, Any], rda : org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]) : MMap[Property.Key, Any] = {

    options(OFAPreprocessModule.globalRdaKey) = rda
    options(rdaKey) = rda

    return options
  }

  def getOFG (options : scala.collection.Map[Property.Key, Any]) : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode] = {
    if (options.contains(OFAPreprocessModule.globalOFGKey)) {
       return options(OFAPreprocessModule.globalOFGKey).asInstanceOf[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]]
    }
    if (options.contains(OFAPreprocessModule.OFGKey)) {
       return options(OFAPreprocessModule.OFGKey).asInstanceOf[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setOFG (options : MMap[Property.Key, Any], OFG : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]) : MMap[Property.Key, Any] = {

    options(OFAPreprocessModule.globalOFGKey) = OFG
    options(OFGKey) = OFG

    return options
  }

  object ConsumerView {
    implicit class OFAPreprocessModuleConsumerView (val job : PropertyProvider) extends AnyVal {
      def procedureSymbolTable : org.sireum.pilar.symbol.ProcedureSymbolTable = OFAPreprocessModule.getProcedureSymbolTable(job.propertyMap)
      def cfg : org.sireum.alir.ControlFlowGraph[java.lang.String] = OFAPreprocessModule.getCfg(job.propertyMap)
      def androidVirtualMethodTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables = OFAPreprocessModule.getAndroidVirtualMethodTables(job.propertyMap)
      def rda : org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]] = OFAPreprocessModule.getRda(job.propertyMap)
      def OFG : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode] = OFAPreprocessModule.getOFG(job.propertyMap)
    }
  }

  object ProducerView {
    implicit class OFAPreprocessModuleProducerView (val job : PropertyProvider) extends AnyVal {

      def procedureSymbolTable_=(procedureSymbolTable : org.sireum.pilar.symbol.ProcedureSymbolTable) { OFAPreprocessModule.setProcedureSymbolTable(job.propertyMap, procedureSymbolTable) }
      def procedureSymbolTable : org.sireum.pilar.symbol.ProcedureSymbolTable = OFAPreprocessModule.getProcedureSymbolTable(job.propertyMap)

      def cfg_=(cfg : org.sireum.alir.ControlFlowGraph[java.lang.String]) { OFAPreprocessModule.setCfg(job.propertyMap, cfg) }
      def cfg : org.sireum.alir.ControlFlowGraph[java.lang.String] = OFAPreprocessModule.getCfg(job.propertyMap)

      def androidVirtualMethodTables_=(androidVirtualMethodTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables) { OFAPreprocessModule.setAndroidVirtualMethodTables(job.propertyMap, androidVirtualMethodTables) }
      def androidVirtualMethodTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables = OFAPreprocessModule.getAndroidVirtualMethodTables(job.propertyMap)

      def rda_=(rda : org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]) { OFAPreprocessModule.setRda(job.propertyMap, rda) }
      def rda : org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]] = OFAPreprocessModule.getRda(job.propertyMap)

      def OFG_=(OFG : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]) { OFAPreprocessModule.setOFG(job.propertyMap, OFG) }
      def OFG : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode] = OFAPreprocessModule.getOFG(job.propertyMap)
    }
  }
}

trait OFAPreprocessModule {
  def job : PipelineJob

  def procedureSymbolTable : org.sireum.pilar.symbol.ProcedureSymbolTable = OFAPreprocessModule.getProcedureSymbolTable(job.propertyMap)

  def cfg : org.sireum.alir.ControlFlowGraph[java.lang.String] = OFAPreprocessModule.getCfg(job.propertyMap)

  def androidVirtualMethodTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidVirtualMethodTables = OFAPreprocessModule.getAndroidVirtualMethodTables(job.propertyMap)

  def rda : org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]] = OFAPreprocessModule.getRda(job.propertyMap)


  def OFG_=(OFG : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode]) { OFAPreprocessModule.setOFG(job.propertyMap, OFG) }
  def OFG : org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode] = OFAPreprocessModule.getOFG(job.propertyMap)
}