// Do not edit this file. It is auto-generated from org.sireum.amandroid.module.OFAsCfg
// by org.sireum.pipeline.gen.ModuleGenerator

package org.sireum.amandroid.module

import org.sireum.util._
import org.sireum.pipeline._
import java.lang.String
import org.sireum.alir.AlirIntraProceduralNode
import org.sireum.alir.ControlFlowGraph
import org.sireum.alir.DefRef
import org.sireum.alir.MonotoneDataFlowAnalysisResult
import org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables
import org.sireum.amandroid.module.AndroidInterIntraProcedural.AndroidInterAnalysisResult
import org.sireum.amandroid.module.AndroidInterIntraProcedural.AndroidIntraAnalysisResult
import org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph
import org.sireum.amandroid.objectflowanalysis.OfaNode
import org.sireum.amandroid.scfg.CompressedControlFlowGraph
import org.sireum.pilar.ast.LocationDecl
import org.sireum.pilar.symbol.ProcedureSymbolTable
import org.sireum.pilar.symbol.SymbolTable
import scala.Function1
import scala.Function2
import scala.Option
import scala.collection.Seq
import scala.collection.mutable.Map

object OFAsCfgModule extends PipelineModule {
  def title = "System Control Flow Graph with OFA Builder"
  def origin = classOf[OFAsCfg]

  val globalOFAsCfgKey = "Global.OFAsCfg"
  val globalProcedureSymbolTablesKey = "Global.procedureSymbolTables"
  val globalAndroidCacheKey = "Global.androidCache"
  val globalAndroidLibInfoTablesKey = "Global.androidLibInfoTables"
  val globalCfgsKey = "Global.cfgs"
  val globalRdasKey = "Global.rdas"
  val OFAsCfgKey = "OFAsCfg.OFAsCfg"
  val globalApkFileLocationKey = "Global.apkFileLocation"
  val globalCCfgsKey = "Global.cCfgs"

  def compute(job : PipelineJob, info : PipelineJobModuleInfo) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    try {
      val module = Class.forName("org.sireum.amandroid.module.OFAsCfgModuleDef")
      val cons = module.getConstructors()(0)
      val params = Array[AnyRef](job, info)
      val inst = cons.newInstance(params : _*)
    } catch {
      case e : Throwable =>
        e.printStackTrace
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, e.getMessage);
    }
    return tags
  }

  override def initialize(job : PipelineJob) {
  }

  override def validPipeline(stage : PipelineStage, job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    val deps = ilist[PipelineModule]()
    deps.foreach(d =>
      if(stage.modules.contains(d)){
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "'" + this.title + "' depends on '" + d.title + "' yet both were found in stage '" + stage.title + "'"
        )
      }
    )
    return tags
  }

  def inputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    var _androidCache : scala.Option[AnyRef] = None
    var _androidCacheKey : scala.Option[String] = None

    val keylistandroidCache = List(OFAsCfgModule.globalAndroidCacheKey)
    keylistandroidCache.foreach(key => 
      if(job ? key) { 
        if(_androidCache.isEmpty) {
          _androidCache = Some(job(key))
          _androidCacheKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _androidCache.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'androidCache' keys '" + _androidCacheKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _androidCache match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'androidCache'.  Expecting 'scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'androidCache'")       
    }
    var _androidLibInfoTables : scala.Option[AnyRef] = None
    var _androidLibInfoTablesKey : scala.Option[String] = None

    val keylistandroidLibInfoTables = List(OFAsCfgModule.globalAndroidLibInfoTablesKey)
    keylistandroidLibInfoTables.foreach(key => 
      if(job ? key) { 
        if(_androidLibInfoTables.isEmpty) {
          _androidLibInfoTables = Some(job(key))
          _androidLibInfoTablesKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _androidLibInfoTables.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'androidLibInfoTables' keys '" + _androidLibInfoTablesKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _androidLibInfoTables match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'androidLibInfoTables'.  Expecting 'org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'androidLibInfoTables'")       
    }
    var _cfgs : scala.Option[AnyRef] = None
    var _cfgsKey : scala.Option[String] = None

    val keylistcfgs = List(OFAsCfgModule.globalCfgsKey)
    keylistcfgs.foreach(key => 
      if(job ? key) { 
        if(_cfgs.isEmpty) {
          _cfgs = Some(job(key))
          _cfgsKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _cfgs.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'cfgs' keys '" + _cfgsKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _cfgs match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'cfgs'.  Expecting 'scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'cfgs'")       
    }
    var _rdas : scala.Option[AnyRef] = None
    var _rdasKey : scala.Option[String] = None

    val keylistrdas = List(OFAsCfgModule.globalRdasKey)
    keylistrdas.foreach(key => 
      if(job ? key) { 
        if(_rdas.isEmpty) {
          _rdas = Some(job(key))
          _rdasKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _rdas.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'rdas' keys '" + _rdasKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _rdas match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'rdas'.  Expecting 'scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'rdas'")       
    }
    var _cCfgs : scala.Option[AnyRef] = None
    var _cCfgsKey : scala.Option[String] = None

    val keylistcCfgs = List(OFAsCfgModule.globalCCfgsKey)
    keylistcCfgs.foreach(key => 
      if(job ? key) { 
        if(_cCfgs.isEmpty) {
          _cCfgs = Some(job(key))
          _cCfgsKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _cCfgs.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'cCfgs' keys '" + _cCfgsKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _cCfgs match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'cCfgs'.  Expecting 'scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'cCfgs'")       
    }
    var _apkFileLocation : scala.Option[AnyRef] = None
    var _apkFileLocationKey : scala.Option[String] = None

    val keylistapkFileLocation = List(OFAsCfgModule.globalApkFileLocationKey)
    keylistapkFileLocation.foreach(key => 
      if(job ? key) { 
        if(_apkFileLocation.isEmpty) {
          _apkFileLocation = Some(job(key))
          _apkFileLocationKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _apkFileLocation.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'apkFileLocation' keys '" + _apkFileLocationKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _apkFileLocation match{
      case Some(x) =>
        if(!x.isInstanceOf[java.lang.String]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'apkFileLocation'.  Expecting 'java.lang.String' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'apkFileLocation'")       
    }
    var _procedureSymbolTables : scala.Option[AnyRef] = None
    var _procedureSymbolTablesKey : scala.Option[String] = None

    val keylistprocedureSymbolTables = List(OFAsCfgModule.globalProcedureSymbolTablesKey)
    keylistprocedureSymbolTables.foreach(key => 
      if(job ? key) { 
        if(_procedureSymbolTables.isEmpty) {
          _procedureSymbolTables = Some(job(key))
          _procedureSymbolTablesKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _procedureSymbolTables.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'procedureSymbolTables' keys '" + _procedureSymbolTablesKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _procedureSymbolTables match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'procedureSymbolTables'.  Expecting 'scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'procedureSymbolTables'")       
    }
    return tags
  }

  def outputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    if(!(job ? OFAsCfgModule.OFAsCfgKey) && !(job ? OFAsCfgModule.globalOFAsCfgKey)) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': No entry found for 'OFAsCfg'. Expecting (OFAsCfgModule.OFAsCfgKey or OFAsCfgModule.globalOFAsCfgKey)") 
    }

    if(job ? OFAsCfgModule.OFAsCfgKey && !job(OFAsCfgModule.OFAsCfgKey).isInstanceOf[scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for OFAsCfgModule.OFAsCfgKey.  Expecting 'scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]' but found '" + 
        job(OFAsCfgModule.OFAsCfgKey).getClass.toString + "'")
    } 

    if(job ? OFAsCfgModule.globalOFAsCfgKey && !job(OFAsCfgModule.globalOFAsCfgKey).isInstanceOf[scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for OFAsCfgModule.globalOFAsCfgKey.  Expecting 'scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]' but found '" + 
        job(OFAsCfgModule.globalOFAsCfgKey).getClass.toString + "'")
    } 
    return tags
  }

  def getAndroidCache (options : scala.collection.Map[Property.Key, Any]) : scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]] = {
    if (options.contains(OFAsCfgModule.globalAndroidCacheKey)) {
       return options(OFAsCfgModule.globalAndroidCacheKey).asInstanceOf[scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setAndroidCache (options : MMap[Property.Key, Any], androidCache : scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]]) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalAndroidCacheKey) = androidCache

    return options
  }

  def getAndroidLibInfoTables (options : scala.collection.Map[Property.Key, Any]) : org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables = {
    if (options.contains(OFAsCfgModule.globalAndroidLibInfoTablesKey)) {
       return options(OFAsCfgModule.globalAndroidLibInfoTablesKey).asInstanceOf[org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setAndroidLibInfoTables (options : MMap[Property.Key, Any], androidLibInfoTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalAndroidLibInfoTablesKey) = androidLibInfoTables

    return options
  }

  def getCfgs (options : scala.collection.Map[Property.Key, Any]) : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]] = {
    if (options.contains(OFAsCfgModule.globalCfgsKey)) {
       return options(OFAsCfgModule.globalCfgsKey).asInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setCfgs (options : MMap[Property.Key, Any], cfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]]) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalCfgsKey) = cfgs

    return options
  }

  def getOFAsCfg (options : scala.collection.Map[Property.Key, Any]) : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]] = {
    if (options.contains(OFAsCfgModule.globalOFAsCfgKey)) {
       return options(OFAsCfgModule.globalOFAsCfgKey).asInstanceOf[scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]]
    }
    if (options.contains(OFAsCfgModule.OFAsCfgKey)) {
       return options(OFAsCfgModule.OFAsCfgKey).asInstanceOf[scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setOFAsCfg (options : MMap[Property.Key, Any], OFAsCfg : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalOFAsCfgKey) = OFAsCfg
    options(OFAsCfgKey) = OFAsCfg

    return options
  }

  def getRdas (options : scala.collection.Map[Property.Key, Any]) : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]] = {
    if (options.contains(OFAsCfgModule.globalRdasKey)) {
       return options(OFAsCfgModule.globalRdasKey).asInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setRdas (options : MMap[Property.Key, Any], rdas : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalRdasKey) = rdas

    return options
  }

  def getCCfgs (options : scala.collection.Map[Property.Key, Any]) : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]] = {
    if (options.contains(OFAsCfgModule.globalCCfgsKey)) {
       return options(OFAsCfgModule.globalCCfgsKey).asInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setCCfgs (options : MMap[Property.Key, Any], cCfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]]) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalCCfgsKey) = cCfgs

    return options
  }

  def getApkFileLocation (options : scala.collection.Map[Property.Key, Any]) : java.lang.String = {
    if (options.contains(OFAsCfgModule.globalApkFileLocationKey)) {
       return options(OFAsCfgModule.globalApkFileLocationKey).asInstanceOf[java.lang.String]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setApkFileLocation (options : MMap[Property.Key, Any], apkFileLocation : java.lang.String) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalApkFileLocationKey) = apkFileLocation

    return options
  }

  def getProcedureSymbolTables (options : scala.collection.Map[Property.Key, Any]) : scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable] = {
    if (options.contains(OFAsCfgModule.globalProcedureSymbolTablesKey)) {
       return options(OFAsCfgModule.globalProcedureSymbolTablesKey).asInstanceOf[scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setProcedureSymbolTables (options : MMap[Property.Key, Any], procedureSymbolTables : scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable]) : MMap[Property.Key, Any] = {

    options(OFAsCfgModule.globalProcedureSymbolTablesKey) = procedureSymbolTables

    return options
  }

  object ConsumerView {
    implicit class OFAsCfgModuleConsumerView (val job : PropertyProvider) extends AnyVal {
      def androidCache : scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]] = OFAsCfgModule.getAndroidCache(job.propertyMap)
      def androidLibInfoTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables = OFAsCfgModule.getAndroidLibInfoTables(job.propertyMap)
      def cfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]] = OFAsCfgModule.getCfgs(job.propertyMap)
      def OFAsCfg : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]] = OFAsCfgModule.getOFAsCfg(job.propertyMap)
      def rdas : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]] = OFAsCfgModule.getRdas(job.propertyMap)
      def cCfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]] = OFAsCfgModule.getCCfgs(job.propertyMap)
      def apkFileLocation : java.lang.String = OFAsCfgModule.getApkFileLocation(job.propertyMap)
      def procedureSymbolTables : scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable] = OFAsCfgModule.getProcedureSymbolTables(job.propertyMap)
    }
  }

  object ProducerView {
    implicit class OFAsCfgModuleProducerView (val job : PropertyProvider) extends AnyVal {

      def androidCache_=(androidCache : scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]]) { OFAsCfgModule.setAndroidCache(job.propertyMap, androidCache) }
      def androidCache : scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]] = OFAsCfgModule.getAndroidCache(job.propertyMap)

      def androidLibInfoTables_=(androidLibInfoTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables) { OFAsCfgModule.setAndroidLibInfoTables(job.propertyMap, androidLibInfoTables) }
      def androidLibInfoTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables = OFAsCfgModule.getAndroidLibInfoTables(job.propertyMap)

      def cfgs_=(cfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]]) { OFAsCfgModule.setCfgs(job.propertyMap, cfgs) }
      def cfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]] = OFAsCfgModule.getCfgs(job.propertyMap)

      def OFAsCfg_=(OFAsCfg : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]) { OFAsCfgModule.setOFAsCfg(job.propertyMap, OFAsCfg) }
      def OFAsCfg : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]] = OFAsCfgModule.getOFAsCfg(job.propertyMap)

      def rdas_=(rdas : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]]) { OFAsCfgModule.setRdas(job.propertyMap, rdas) }
      def rdas : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]] = OFAsCfgModule.getRdas(job.propertyMap)

      def cCfgs_=(cCfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]]) { OFAsCfgModule.setCCfgs(job.propertyMap, cCfgs) }
      def cCfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]] = OFAsCfgModule.getCCfgs(job.propertyMap)

      def apkFileLocation_=(apkFileLocation : java.lang.String) { OFAsCfgModule.setApkFileLocation(job.propertyMap, apkFileLocation) }
      def apkFileLocation : java.lang.String = OFAsCfgModule.getApkFileLocation(job.propertyMap)

      def procedureSymbolTables_=(procedureSymbolTables : scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable]) { OFAsCfgModule.setProcedureSymbolTables(job.propertyMap, procedureSymbolTables) }
      def procedureSymbolTables : scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable] = OFAsCfgModule.getProcedureSymbolTables(job.propertyMap)
    }
  }
}

trait OFAsCfgModule {
  def job : PipelineJob

  def androidCache : scala.Option[org.sireum.amandroid.cache.AndroidCacheFile[java.lang.String]] = OFAsCfgModule.getAndroidCache(job.propertyMap)

  def androidLibInfoTables : org.sireum.amandroid.AndroidSymbolResolver.AndroidLibInfoTables = OFAsCfgModule.getAndroidLibInfoTables(job.propertyMap)

  def cfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.ControlFlowGraph[java.lang.String]] = OFAsCfgModule.getCfgs(job.propertyMap)


  def OFAsCfg_=(OFAsCfg : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]]) { OFAsCfgModule.setOFAsCfg(job.propertyMap, OFAsCfg) }
  def OFAsCfg : scala.collection.mutable.Map[java.lang.String, scala.Tuple2[org.sireum.amandroid.objectflowanalysis.ObjectFlowGraph[org.sireum.amandroid.objectflowanalysis.OfaNode], org.sireum.amandroid.scfg.SystemControlFlowGraph[java.lang.String]]] = OFAsCfgModule.getOFAsCfg(job.propertyMap)

  def rdas : scala.collection.mutable.Map[java.lang.String, org.sireum.alir.MonotoneDataFlowAnalysisResult[scala.Tuple2[org.sireum.alir.Slot, org.sireum.alir.DefDesc]]] = OFAsCfgModule.getRdas(job.propertyMap)

  def cCfgs : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.scfg.CompressedControlFlowGraph[java.lang.String]] = OFAsCfgModule.getCCfgs(job.propertyMap)

  def apkFileLocation : java.lang.String = OFAsCfgModule.getApkFileLocation(job.propertyMap)

  def procedureSymbolTables : scala.collection.Seq[org.sireum.pilar.symbol.ProcedureSymbolTable] = OFAsCfgModule.getProcedureSymbolTables(job.propertyMap)
}