// Do not edit this file. It is auto-generated from org.sireum.amandroid.module.AndroidInterProcedural
// by org.sireum.pipeline.gen.ModuleGenerator

package org.sireum.amandroid.module

import org.sireum.util._
import org.sireum.pipeline._
import java.lang.String
import org.sireum.amandroid.android.appInfo.PrepareApp
import org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult
import org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult
import org.sireum.pilar.symbol.SymbolTable
import scala.Option
import scala.collection.mutable.Map

object AndroidInterProceduralModule extends PipelineModule {
  def title = "Android InterProcedural Module"
  def origin = classOf[AndroidInterProcedural]

  val globalParallelKey = "Global.parallel"
  val globalInterResultKey = "Global.interResult"
  val globalAppInfoOptKey = "Global.appInfoOpt"
  val globalShouldBuildCallGraphKey = "Global.shouldBuildCallGraph"
  val globalIntraResultKey = "Global.intraResult"
  val globalSymbolTableKey = "Global.symbolTable"

  def compute(job : PipelineJob, info : PipelineJobModuleInfo) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    try {
      val module = Class.forName("org.sireum.amandroid.module.AndroidInterProceduralModuleDef")
      val cons = module.getConstructors()(0)
      val params = Array[AnyRef](job, info)
      val inst = cons.newInstance(params : _*)
    } catch {
      case e : Throwable =>
        e.printStackTrace
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, e.getMessage);
    }
    return tags
  }

  override def initialize(job : PipelineJob) {
    if(!(job ? AndroidInterProceduralModule.globalShouldBuildCallGraphKey)) {
      val shouldBuildCallGraph = Class.forName("org.sireum.amandroid.module.AndroidInterProcedural").getDeclaredMethod("$lessinit$greater$default$4").invoke(null).asInstanceOf[scala.Boolean]
      setShouldBuildCallGraph(job.propertyMap, shouldBuildCallGraph)
    }

    if(!(job ? AndroidInterProceduralModule.globalAppInfoOptKey)) {
      val appInfoOpt = Class.forName("org.sireum.amandroid.module.AndroidInterProcedural").getDeclaredMethod("$lessinit$greater$default$5").invoke(null).asInstanceOf[scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp]]
      setAppInfoOpt(job.propertyMap, appInfoOpt)
    }
  }

  override def validPipeline(stage : PipelineStage, job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    val deps = ilist[PipelineModule]()
    deps.foreach(d =>
      if(stage.modules.contains(d)){
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "'" + this.title + "' depends on '" + d.title + "' yet both were found in stage '" + stage.title + "'"
        )
      }
    )
    return tags
  }

  def inputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    var _parallel : scala.Option[AnyRef] = None
    var _parallelKey : scala.Option[String] = None

    val keylistparallel = List(AndroidInterProceduralModule.globalParallelKey)
    keylistparallel.foreach(key => 
      if(job ? key) { 
        if(_parallel.isEmpty) {
          _parallel = Some(job(key))
          _parallelKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _parallel.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'parallel' keys '" + _parallelKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _parallel match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.Boolean]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'parallel'.  Expecting 'scala.Boolean' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'parallel'")       
    }
    var _symbolTable : scala.Option[AnyRef] = None
    var _symbolTableKey : scala.Option[String] = None

    val keylistsymbolTable = List(AndroidInterProceduralModule.globalSymbolTableKey)
    keylistsymbolTable.foreach(key => 
      if(job ? key) { 
        if(_symbolTable.isEmpty) {
          _symbolTable = Some(job(key))
          _symbolTableKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _symbolTable.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'symbolTable' keys '" + _symbolTableKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _symbolTable match{
      case Some(x) =>
        if(!x.isInstanceOf[org.sireum.pilar.symbol.SymbolTable]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'symbolTable'.  Expecting 'org.sireum.pilar.symbol.SymbolTable' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'symbolTable'")       
    }
    var _shouldBuildCallGraph : scala.Option[AnyRef] = None
    var _shouldBuildCallGraphKey : scala.Option[String] = None

    val keylistshouldBuildCallGraph = List(AndroidInterProceduralModule.globalShouldBuildCallGraphKey)
    keylistshouldBuildCallGraph.foreach(key => 
      if(job ? key) { 
        if(_shouldBuildCallGraph.isEmpty) {
          _shouldBuildCallGraph = Some(job(key))
          _shouldBuildCallGraphKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _shouldBuildCallGraph.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'shouldBuildCallGraph' keys '" + _shouldBuildCallGraphKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _shouldBuildCallGraph match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.Boolean]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'shouldBuildCallGraph'.  Expecting 'scala.Boolean' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'shouldBuildCallGraph'")       
    }
    var _appInfoOpt : scala.Option[AnyRef] = None
    var _appInfoOptKey : scala.Option[String] = None

    val keylistappInfoOpt = List(AndroidInterProceduralModule.globalAppInfoOptKey)
    keylistappInfoOpt.foreach(key => 
      if(job ? key) { 
        if(_appInfoOpt.isEmpty) {
          _appInfoOpt = Some(job(key))
          _appInfoOptKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _appInfoOpt.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'appInfoOpt' keys '" + _appInfoOptKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _appInfoOpt match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'appInfoOpt'.  Expecting 'scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'appInfoOpt'")       
    }
    var _intraResult : scala.Option[AnyRef] = None
    var _intraResultKey : scala.Option[String] = None

    val keylistintraResult = List(AndroidInterProceduralModule.globalIntraResultKey)
    keylistintraResult.foreach(key => 
      if(job ? key) { 
        if(_intraResult.isEmpty) {
          _intraResult = Some(job(key))
          _intraResultKey = Some(key)
        }
        if(!(job(key).asInstanceOf[AnyRef] eq _intraResult.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'intraResult' keys '" + _intraResultKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _intraResult match{
      case Some(x) =>
        if(!x.isInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult]]){
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'intraResult'.  Expecting 'scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'intraResult'")       
    }
    return tags
  }

  def outputDefined (job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    if(!(job ? AndroidInterProceduralModule.globalInterResultKey)) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': No entry found for 'interResult'. Expecting (AndroidInterProceduralModule.globalInterResultKey)") 
    }

    if(job ? AndroidInterProceduralModule.globalInterResultKey && !job(AndroidInterProceduralModule.globalInterResultKey).isInstanceOf[org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, 
        "Output error for '" + this.title + "': Wrong type found for AndroidInterProceduralModule.globalInterResultKey.  Expecting 'org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult' but found '" + 
        job(AndroidInterProceduralModule.globalInterResultKey).getClass.toString + "'")
    } 
    return tags
  }

  def getParallel (options : scala.collection.Map[Property.Key, Any]) : scala.Boolean = {
    if (options.contains(AndroidInterProceduralModule.globalParallelKey)) {
       return options(AndroidInterProceduralModule.globalParallelKey).asInstanceOf[scala.Boolean]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setParallel (options : MMap[Property.Key, Any], parallel : scala.Boolean) : MMap[Property.Key, Any] = {

    options(AndroidInterProceduralModule.globalParallelKey) = parallel

    return options
  }

  def getSymbolTable (options : scala.collection.Map[Property.Key, Any]) : org.sireum.pilar.symbol.SymbolTable = {
    if (options.contains(AndroidInterProceduralModule.globalSymbolTableKey)) {
       return options(AndroidInterProceduralModule.globalSymbolTableKey).asInstanceOf[org.sireum.pilar.symbol.SymbolTable]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setSymbolTable (options : MMap[Property.Key, Any], symbolTable : org.sireum.pilar.symbol.SymbolTable) : MMap[Property.Key, Any] = {

    options(AndroidInterProceduralModule.globalSymbolTableKey) = symbolTable

    return options
  }

  def getShouldBuildCallGraph (options : scala.collection.Map[Property.Key, Any]) : scala.Boolean = {
    if (options.contains(AndroidInterProceduralModule.globalShouldBuildCallGraphKey)) {
       return options(AndroidInterProceduralModule.globalShouldBuildCallGraphKey).asInstanceOf[scala.Boolean]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setShouldBuildCallGraph (options : MMap[Property.Key, Any], shouldBuildCallGraph : scala.Boolean) : MMap[Property.Key, Any] = {

    options(AndroidInterProceduralModule.globalShouldBuildCallGraphKey) = shouldBuildCallGraph

    return options
  }

  def getAppInfoOpt (options : scala.collection.Map[Property.Key, Any]) : scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp] = {
    if (options.contains(AndroidInterProceduralModule.globalAppInfoOptKey)) {
       return options(AndroidInterProceduralModule.globalAppInfoOptKey).asInstanceOf[scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setAppInfoOpt (options : MMap[Property.Key, Any], appInfoOpt : scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp]) : MMap[Property.Key, Any] = {

    options(AndroidInterProceduralModule.globalAppInfoOptKey) = appInfoOpt

    return options
  }

  def getIntraResult (options : scala.collection.Map[Property.Key, Any]) : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult] = {
    if (options.contains(AndroidInterProceduralModule.globalIntraResultKey)) {
       return options(AndroidInterProceduralModule.globalIntraResultKey).asInstanceOf[scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setIntraResult (options : MMap[Property.Key, Any], intraResult : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult]) : MMap[Property.Key, Any] = {

    options(AndroidInterProceduralModule.globalIntraResultKey) = intraResult

    return options
  }

  def getInterResult (options : scala.collection.Map[Property.Key, Any]) : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult = {
    if (options.contains(AndroidInterProceduralModule.globalInterResultKey)) {
       return options(AndroidInterProceduralModule.globalInterResultKey).asInstanceOf[org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setInterResult (options : MMap[Property.Key, Any], interResult : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult) : MMap[Property.Key, Any] = {

    options(AndroidInterProceduralModule.globalInterResultKey) = interResult

    return options
  }

  object ConsumerView {
    implicit class AndroidInterProceduralModuleConsumerView (val job : PropertyProvider) extends AnyVal {
      def parallel : scala.Boolean = AndroidInterProceduralModule.getParallel(job.propertyMap)
      def symbolTable : org.sireum.pilar.symbol.SymbolTable = AndroidInterProceduralModule.getSymbolTable(job.propertyMap)
      def shouldBuildCallGraph : scala.Boolean = AndroidInterProceduralModule.getShouldBuildCallGraph(job.propertyMap)
      def appInfoOpt : scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp] = AndroidInterProceduralModule.getAppInfoOpt(job.propertyMap)
      def intraResult : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult] = AndroidInterProceduralModule.getIntraResult(job.propertyMap)
      def interResult : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult = AndroidInterProceduralModule.getInterResult(job.propertyMap)
    }
  }

  object ProducerView {
    implicit class AndroidInterProceduralModuleProducerView (val job : PropertyProvider) extends AnyVal {

      def parallel_=(parallel : scala.Boolean) { AndroidInterProceduralModule.setParallel(job.propertyMap, parallel) }
      def parallel : scala.Boolean = AndroidInterProceduralModule.getParallel(job.propertyMap)

      def symbolTable_=(symbolTable : org.sireum.pilar.symbol.SymbolTable) { AndroidInterProceduralModule.setSymbolTable(job.propertyMap, symbolTable) }
      def symbolTable : org.sireum.pilar.symbol.SymbolTable = AndroidInterProceduralModule.getSymbolTable(job.propertyMap)

      def shouldBuildCallGraph_=(shouldBuildCallGraph : scala.Boolean) { AndroidInterProceduralModule.setShouldBuildCallGraph(job.propertyMap, shouldBuildCallGraph) }
      def shouldBuildCallGraph : scala.Boolean = AndroidInterProceduralModule.getShouldBuildCallGraph(job.propertyMap)

      def appInfoOpt_=(appInfoOpt : scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp]) { AndroidInterProceduralModule.setAppInfoOpt(job.propertyMap, appInfoOpt) }
      def appInfoOpt : scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp] = AndroidInterProceduralModule.getAppInfoOpt(job.propertyMap)

      def intraResult_=(intraResult : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult]) { AndroidInterProceduralModule.setIntraResult(job.propertyMap, intraResult) }
      def intraResult : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult] = AndroidInterProceduralModule.getIntraResult(job.propertyMap)

      def interResult_=(interResult : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult) { AndroidInterProceduralModule.setInterResult(job.propertyMap, interResult) }
      def interResult : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult = AndroidInterProceduralModule.getInterResult(job.propertyMap)
    }
  }
}

trait AndroidInterProceduralModule {
  def job : PipelineJob

  def parallel : scala.Boolean = AndroidInterProceduralModule.getParallel(job.propertyMap)

  def symbolTable : org.sireum.pilar.symbol.SymbolTable = AndroidInterProceduralModule.getSymbolTable(job.propertyMap)

  def shouldBuildCallGraph : scala.Boolean = AndroidInterProceduralModule.getShouldBuildCallGraph(job.propertyMap)

  def appInfoOpt : scala.Option[org.sireum.amandroid.android.appInfo.PrepareApp] = AndroidInterProceduralModule.getAppInfoOpt(job.propertyMap)

  def intraResult : scala.collection.mutable.Map[java.lang.String, org.sireum.amandroid.module.AndroidIntraProcedural.AndroidIntraAnalysisResult] = AndroidInterProceduralModule.getIntraResult(job.propertyMap)


  def interResult_=(interResult : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult) { AndroidInterProceduralModule.setInterResult(job.propertyMap, interResult) }
  def interResult : org.sireum.amandroid.module.AndroidInterProcedural.AndroidInterAnalysisResult = AndroidInterProceduralModule.getInterResult(job.propertyMap)
}